# Generated by Django 3.2.13 on 2024-09-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_orders', '0001_create_initial_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='apps_orders',
        ),
    ]
