# Generated by Django 3.2.13 on 2024-09-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ID',
            new_name='id',
        ),
    ]
