# Generated by Django 3.2.13 on 2024-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Принят'), (2, 'В процессе'), (3, 'Выполнен')], default=1),
        ),
    ]
