# Generated by Django 3.2.13 on 2024-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_orders', '0002_rename_id_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Не срочно'), (2, 'Средне'), (3, 'Срочно')], default=1),
        ),
    ]
