# Generated by Django 3.2.13 on 2024-10-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_orders', '0004_order_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_tg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
