# Generated by Django 3.2.13 on 2024-10-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_orders', '0005_auto_20241001_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_name',
            new_name='client_fio',
        ),
    ]
