# Generated by Django 3.2.13 on 2024-10-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_products', '0004_remove_product_description'),
        ('apps_orders', '0006_rename_client_name_order_client_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps_products.product'),
            preserve_default=False,
        ),
    ]
