services:
  epox-money-manager:
    container_name: epox_money_manager
    restart: always
    env_file: .env
    build: .
    environment:
      - NGROK_URL=value
    networks:
      - app_network
    ports:
      - "5005:5005"  # Пробросим порт 5005 для Gunicorn
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:5005"

  postgres:
    container_name: postgres
    restart: always
    image: "postgres:latest"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
    environment:
      POSTGRES_DB: "epox_money_manager"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "superSecretPassword"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - app_network

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    depends_on:
      - epox-money-manager
    environment:
      NGROK_AUTHTOKEN: "2XWRYI678AX94KVSwTpKS3o36sD_57iutsiwFMTWLFrp61sn"
      NGROK_PORT: "epox_money_manager:5005"  # Пробросим порт 5005 для ngrok
    ports:
      - "4040:4040" # для веб-интерфейса  
    networks:
      - app_network  # Используем одну и ту же сеть
    command: "http epox_money_manager:5005"

networks:
  app_network:
    driver: bridge
